{% macro delete_ssp_demand_detail() %}
WITH last_run_date_cte AS (
    SELECT LAST_RUN_DATE
    FROM CBI_METADATA.A_INTERFACE_RUN
    WHERE INTERFACE_NAME = 'INT_SSP_DEMAND_DETAIL_BIMA_IMP'
)
DELETE FROM LND_MANUAL_ENTRY.SSP_DEMAND_DETAIL
WHERE DEMAND_SET_NAME IN (
    SELECT DISTINCT DEMAND_SET_NAME
    FROM LND_EXT_FILES.SSP_DEMAND_DETAIL
    CROSS JOIN last_run_date_cte lr
    WHERE CREATE_DT > lr.LAST_RUN_DATE
)
{% endmacro %}
