{% macro delete_ssp_demand_detail() %}
    DELETE FROM LND_MANUAL_ENTRY.SSP_DEMAND_DETAIL
    WHERE DEMAND_SET_NAME IN (
        SELECT DISTINCT DEMAND_SET_NAME
        FROM LND_EXT_FILES.SSP_DEMAND_DETAIL
        WHERE CREATE_DT > (
            SELECT LAST_RUN_DATE FROM CBI_METADATA.A_INTERFACE_RUN
            WHERE INTERFACE_NAME = 'INT_SSP_DEMAND_DETAIL_BIMA_IMP'
        )
    )
{% endmacro %}
