{{
    config(
        materialized='table'
    )
}}

SELECT
    SRC.DEMAND_SET,
    SRC.DEMAND_SET_NAME,
    SRC.DEMAND_TYPE_CD,
    SRC.ITEM_02_CD,
    SRC.LOCATION,
    SRC.BLEND_CD,
    SRC.DEMAND_QTY,
    SRC.UOM_CD,
    SRC.DEMAND_DT,
    SRC.RECOMMENDED_START_DT,
    SRC.RECOMMENDED_END_DT,
    SRC.MONTH,
    SRC.YEAR,
    SRC.NEW_ITEM_CD,
    SRC.ADDRESS_CD,
    SRC.BRAND_CD,
    SRC.VARIETAL_CD,
    SRC.SUB_BRAND_CD,
    SRC.ITEM_SIZE_CD,
    SRC.OPCO_DSC,
    SRC.ACTIVE_FLG,
    SRC.DATA_SRC,
    SRC.CREATE_DT,
    SRC.CREATE_BY,
    SRC.CREATE_PGM,
    SRC.UPDATE_DT,
    SRC.UPDATE_BY,
    SRC.UPDATE_PGM
FROM {{ ref('ssp_demand_detail') }} SRC
WHERE (1=1)
