{{
    config(
        materialized='table',
        post_hook=['{{ update_interface_run_detail_bima_imp() }}']
    )
}}

SELECT
    DEMAND_SET,
    DEMAND_SET_NAME,
    DEMAND_TYPE_CD,
    ITEM_02_CD,
    LOCATION,
    BLEND_CD,
    DEMAND_QTY,
    UOM_CD,
    DEMAND_DT,
    RECOMMENDED_START_DT,
    RECOMMENDED_END_DT,
    MONTH,
    YEAR,
    NEW_ITEM_CD,
    ADDRESS_CD,
    BRAND_CD,
    VARIETAL_CD,
    SUB_BRAND_CD,
    ITEM_SIZE_CD,
    OPCO_DSC,
    ACTIVE_FLG,
    DATA_SRC,
    CREATE_DT,
    CREATE_BY,
    CREATE_PGM,
    UPDATE_DT,
    UPDATE_BY,
    UPDATE_PGM
FROM {{ ref('ssp_demand_detail') }}
WHERE
    (1=1)
