-- ========================================
-- DDL and Sample Data for PKG_SSP_TANK_DETAIL Testing
-- ========================================
-- Date: July 7, 2025
-- Purpose: Create source tables and populate with dummy data for testing

-- Create schemas if they don't exist
CREATE SCHEMA IF NOT EXISTS LND_MANUAL_ENTRY;
CREATE SCHEMA IF NOT EXISTS STG_EDW;

-- ========================================
-- 1. LND_MANUAL_ENTRY.SSP_RR_CALENDAR
-- ========================================
-- This is the main source table for the tank detail processing

CREATE OR REPLACE TABLE LND_MANUAL_ENTRY.SSP_RR_CALENDAR (
    CALENDAR_YEAR NUMBER(4) NOT NULL,
    CALENDAR_MONTH NUMBER(2) NOT NULL,
    ACTIVE_FLG VARCHAR(1) NOT NULL DEFAULT 'Y',

    -- Audit columns (Oracle style)
    CREATE_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATE_BY VARCHAR(50) DEFAULT 'SYSTEM',
    CREATE_PGM VARCHAR(100) DEFAULT 'DDL_SETUP',
    UPDATE_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_BY VARCHAR(50) DEFAULT 'SYSTEM',
    UPDATE_PGM VARCHAR(100) DEFAULT 'DDL_SETUP',

    -- Primary key
    CONSTRAINT PK_SSP_RR_CALENDAR PRIMARY KEY (CALENDAR_YEAR, CALENDAR_MONTH)
);

-- Insert dummy data for testing (2023-2025)
INSERT INTO LND_MANUAL_ENTRY.SSP_RR_CALENDAR (
    CALENDAR_YEAR,
    CALENDAR_MONTH,
    ACTIVE_FLG,
    CREATE_DT,
    CREATE_BY,
    CREATE_PGM
) VALUES
-- 2023 data
(2023, 1, 'Y', '2023-01-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 2, 'Y', '2023-02-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 3, 'Y', '2023-03-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 4, 'Y', '2023-04-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 5, 'Y', '2023-05-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 6, 'Y', '2023-06-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 7, 'Y', '2023-07-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 8, 'Y', '2023-08-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 9, 'Y', '2023-09-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 10, 'Y', '2023-10-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 11, 'Y', '2023-11-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2023, 12, 'Y', '2023-12-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),

-- 2024 data
(2024, 1, 'Y', '2024-01-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 2, 'Y', '2024-02-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 3, 'Y', '2024-03-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 4, 'Y', '2024-04-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 5, 'Y', '2024-05-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 6, 'Y', '2024-06-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 7, 'Y', '2024-07-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 8, 'Y', '2024-08-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 9, 'Y', '2024-09-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 10, 'Y', '2024-10-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 11, 'Y', '2024-11-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2024, 12, 'Y', '2024-12-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),

-- 2025 data (current year)
(2025, 1, 'Y', '2025-01-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 2, 'Y', '2025-02-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 3, 'Y', '2025-03-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 4, 'Y', '2025-04-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 5, 'Y', '2025-05-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 6, 'Y', '2025-06-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 7, 'Y', '2025-07-07'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'), -- Current date
(2025, 8, 'N', '2025-08-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'), -- Inactive for testing
(2025, 9, 'Y', '2025-09-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 10, 'Y', '2025-10-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 11, 'Y', '2025-11-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD'),
(2025, 12, 'Y', '2025-12-01'::TIMESTAMP, 'SETUP', 'DDL_INITIAL_LOAD');

-- ========================================
-- 2. Target Tables (will be managed by dbt)
-- ========================================
-- These are created for reference but will be managed by dbt

-- Final tank detail table (incremental target)
CREATE OR REPLACE TABLE LND_MANUAL_ENTRY.SSP_TANK_DETAIL (
    CALENDAR_YEAR NUMBER(4),
    PROCESSING_TYPE VARCHAR(50),
    VARIETY_CLASSIFICATION VARCHAR(50),
    APP_RECORD_COUNT NUMBER,
    TOTAL_BLEND_KEY NUMBER,
    VARIETY_ADJUSTED_KEY NUMBER,
    EXPRESSION_HASH NUMBER,
    PART_VAL_DATE DATE,
    PART_VAL_STRING VARCHAR(20),
    FINAL_CALCULATION NUMBER,

    -- Oracle-style audit columns
    CREATE_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATE_BY VARCHAR(50) DEFAULT 'DBT_PIPELINE',
    CREATE_PGM VARCHAR(100) DEFAULT 'PKG_SSP_TANK_DETAIL',
    UPDATE_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_BY VARCHAR(50) DEFAULT 'DBT_PIPELINE',
    UPDATE_PGM VARCHAR(100) DEFAULT 'PKG_SSP_TANK_DETAIL',

    -- dbt metadata
    _DBT_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _DBT_RUN_STARTED_AT VARCHAR(50)
);

-- BIMA tank detail table (incremental target)
CREATE OR REPLACE TABLE LND_MANUAL_ENTRY.SSP_TANK_DETAIL_BIMA (
    BIMA_TANK_DETAIL_KEY VARCHAR(32),
    TANK_DETAIL_KEY VARCHAR(32),
    CALENDAR_YEAR NUMBER(4),
    APPLICATION_TYPE VARCHAR(50),
    VARIETY_TYPE VARCHAR(50),
    VARIETY_GRADE VARCHAR(50),
    BIMA_SEASON_TYPE VARCHAR(50),
    BIMA_ADJUSTED_VALUE NUMBER,
    BIMA_QUALITY_SCORE NUMBER,
    BIMA_VOLUME_CATEGORY VARCHAR(50),
    BIMA_RISK_CATEGORY VARCHAR(50),
    BIMA_COMPLIANCE_STATUS VARCHAR(50),
    TOTAL_RECORDS NUMBER,

    -- Dates
    EARLIEST_DATE DATE,
    LATEST_DATE DATE,
    DATE_RANGE_DAYS NUMBER,

    -- Processing metadata
    BIMA_PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BIMA_PROCESS_TYPE VARCHAR(50) DEFAULT 'BIMA_CONVERSION'
);

-- ========================================
-- 3. Verification Queries
-- ========================================

-- Verify calendar data
SELECT
    'Calendar Records' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT,
    MIN(CALENDAR_YEAR) AS MIN_YEAR,
    MAX(CALENDAR_YEAR) AS MAX_YEAR,
    SUM(CASE WHEN ACTIVE_FLG = 'Y' THEN 1 ELSE 0 END) AS ACTIVE_COUNT,
    SUM(CASE WHEN ACTIVE_FLG = 'N' THEN 1 ELSE 0 END) AS INACTIVE_COUNT
FROM LND_MANUAL_ENTRY.SSP_RR_CALENDAR;

-- Show sample data
SELECT
    CALENDAR_YEAR,
    CALENDAR_MONTH,
    ACTIVE_FLG,
    CREATE_DT
FROM LND_MANUAL_ENTRY.SSP_RR_CALENDAR
WHERE CALENDAR_YEAR = 2025
ORDER BY CALENDAR_MONTH;

-- ========================================
-- 4. Cleanup Commands (for testing iterations)
-- ========================================
/*
-- Use these commands to clean up during testing:

-- Drop and recreate tables
DROP TABLE IF EXISTS LND_MANUAL_ENTRY.SSP_TANK_DETAIL;
DROP TABLE IF EXISTS LND_MANUAL_ENTRY.SSP_TANK_DETAIL_BIMA;
DROP TABLE IF EXISTS LND_MANUAL_ENTRY.SSP_RR_CALENDAR;

-- Drop schemas if needed
-- DROP SCHEMA IF EXISTS LND_MANUAL_ENTRY;
-- DROP SCHEMA IF EXISTS STG_EDW;
*/
